import path from 'path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

const ICON_192 = [
  'data:image/png;base64,',
  'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAFHUlEQVR4nO3czW4TMRSG4VPUHQuurFK6z+Vl30i9sSKVdVigUSchnZkkts/P9z5bQhns89oD',
  'RTx9nD5PBoj64f0AgCcCgDQCgDQCgDQCgDQCgDQCgDQCgDQCgDQCgDQCgDQCgDQCgDQCgDQCgLRn7weo6Jf9/PbHftufZp+bfwb34QZobGmo5z/e4nNrXwPr',
  'CADSCADSCADSCADSCADSCADSCMDB/rhv+jncj2+ENTIN6/vuzflJcAsCuFOU03n+HIfdwfFJciKAjaIM/JLLZySIdQSwIMPQL+F2WEcAV2Qf/Gum3xMhnCOA',
  'mYqDf4kQzhGAaQz+JUL4RzoAxcG/pB6CZAAM/v9UQ5AKgMFfpxaCRAAM/u1UQij/b4EY/sdUX7/SAVTfvFEqr2PJV6DKG+al6itRuRuA4e+r2vqWCqDa5kRV',
  'aZ1LvAJV2pAsqrwSpb8BGH5f2dc/dQDZF7+KzPuQNoDMi15R1v1IGUDWxa4u476kCyDjIivJtj+pAsi2uKoy7VOaADItKvLsV4oAsiwmzmXYtxQBZPJyfF39',
  'zNb/POt997b49bb8Wlj29HH6PHk/xJIMp8h3Wv4vcZmHPfJ3i0PfAAx/v683UuR9DBtA5EVb02tYiaC9sAEAI4QMIOppsUXvU5pboK1wAURcJLQTbX9DBRBt',
  'cdBHpH0OFQAwWpgAIp0K6C/KfocJAPAQIoAopwHGirDvIQIAvLgHEOEUgB/v/XcPAPDkGoB3/YjBcw64ASDNLQBOf8x5zQM3AKS5BMDpj2s85oIbANKGB8Dp',
  'jyWj54MbANIIANKGBsDrD7YYOSfcAJBGAJBGAJA2LADe/3GLUfPCDQBpBABpBABpQwLg/R/3GDE33ACQRgCQRgCQRgCQRgCQ1j0A/gYIj+g9P9wAkEYAkEYA',
  'kEYAkEYAkEYAkEYAkEYAkEYAkEYAkEYAkEYAkEYAkEYAkEYAkEYAkNY9gMPu0PuXQGG954cbANIIANIIANIIANIIANKGBMDfBOEeI+aGGwDSCADSCADShgXA',
  'nwNwi1Hzwg0AaQQAaQQAaUMD4M8B2GLknHADQBoBQNrwAHgNwpLR88ENAGkuAXAL4BqPueAGgDS3ALgFMOc1D9wAkOYaALcAzHzngBsA0twD4BbQ5r3/7gEA',
  'nkIE4H0KwEeEfQ8RAOAlTAARTgOME2W/wwQAeAgVQJRTAX1F2udQAZjFWhy0F21/wwVgFm+RbvFyfE399XuKuK8hAwBGCRtAxNNiq16nNKd/e2EDMIu7aFu0',
  'HlaGv4+nj9Pnyfsh1uyPe+9HeMj77u3un5t58M1iD7+Z2bP3AyjIPsSVhX4FmkQ/RXBdhn1LEYBZjsXElyz7lSYAszyLqi7TPqUKwCzX4irKtj/pAjDLt8gq',
  'Mu5LygDMci52ZVn3I20AZnkXvZrM+5A6ALPci19B9vVP8Z3grbJ/xziT7IM/SX8DzFXZlOgqrXOpAMxqbU5E1da31CvQJV6J2qk2+JNyN8Bc1U0brfI6lg7A',
  'rPbmjVB9/Uq/Al3ilWi76oM/kQpgQgjfUxn8iWQAE0L4ojb4E+kAJsohqA7+hABmlEJQH/wJAVxROQQG/xwBLKgUAoN/HQFslDEGhn4dAdwpYhAM/O0IoBGP',
  'IBj4xxFAZy3CYND7IQBIK/+P4YAlBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpBABpfwFLQ3qh',
  '0/0OlAAAAABJRU5ErkJggg==',
].join('');

const ICON_512 = [
  'data:image/png;base64,',
  'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAPLUlEQVR4nO3cu25cRxaGUUpQNsE8mQE61+MplwC9mAxoYk4gN0RSfTm3OrWr/rUyByZP26y9',
  'P1a39OHHy8+XJwAgysfeDwAAnE8AAEAgAQAAgQQAAAQSAAAQSAAAQCABAACBBAAABBIAABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQSAAA',
  'QCABAACBBAAABBIAABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQSAAAQCABAACBBAAABBIAABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAA',
  'gQQAAAQSAAAQ6FPvBwDe+u/Tfzb/u/88/W+K77Hm+wDbuAGAQvYuzSX//gjf46ivAdwmAKCIoxbeva8z0vc4+msBbwkAKODoRXft6434PVp9TUAAAEAkAQAA',
  'gQQAAAQSAAAQSAAAQCABAACBBAAABBIAABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQ6FPvBwDa+Pzt85t//v78tdOTABUJAGAzkQHj8hYA',
  'dPZ+iQKcwQ0AnMiyB6oQANCIZQ9UJgDgIBZ+O+//2355/tLpSWAeAgA2svD7EQSwnwCAhSz8ugQBrCcA4A5Lf0yv/7+JAbhOAMA7lv5cxABcJwDgydJPIQbg',
  'NwFALEs/mxggnQAgiqXPNWKARAKA6Vn6rCEGSCEAmJbFz16XnyEhwIwEANOx+DmaEGBGAoApWPqcwdsDzEQAMDSLn17cCjA6AcCQLH6qEAKMSgAwFIufqoQA',
  'oxEADMHiZxRCgFEIAEqz+BmVEKA6AUBJFj+zEAJUJQAoxeJnVkKAagQAJVj8pBACVCEA6MriJ5UQoLePvR+AXJY/OAf04waA0xl48JbbAHoQAJzG4of7hABn',
  '8hYAp7D8YTnnhTO4AaApgwy2cRtAa24AaMbyh/2cI1pxA8DhDCw4ltsAWnADwKEsf2jH+eJIbgA4hMEE53AbwFHcALCb5Q/nc+7Yyw0AmxlA0JfbAPZwA8Am',
  'lj/U4TyyhQBgNcMG6nEuWctbACxmwEBt3hJgDTcALGL5wzicV5YQADxkmMB4nFse8RYANxkgMDZvCXCPGwCusvxhHs4z1wgA/mBYwHyca94TALxhSMC8nG9e',
  '8xkAnp6eDAZI4XMBXLgBwPKHQM49AiCcIQC5nP9sAiCYww+YA7kEQCiHHrgwDzIJgEAOO/CeuZBHAIRxyIFbzIcsAiCIww08Yk7kEAAhHGpgKfMigwAI4DAD',
  'a5kb8xMAk3OIga3Mj7kJgIk5vMBe5si8BMCkHFrgKObJnATAhBxW4GjmynwEwGQcUqAV82UuAmAiDifQmjkzDwEwCYcSOIt5MwcBMAGHETibuTM+ATA4hxDo',
  'xfwZmwAYmMMH9GYOjUsADMqhA6owj8YkAAbksAHVmEvjEQCDcciAqsynsQgAAAgkAAairuf117e/m3+9Eb9Hq69JO+bUOATAIByq+R216O59nZG+x9Ffi/OY',
  'V2P48OPl50vvh+A+hynL9+evvR9hkUfLee/rsPzH9+X5S+9H4A4BUJzlzy2VQsGy5hYRUNen3g8ArFNp8V9cnkkIwDjcABTmt39eq7j4bxECvOYWoCYfAizK',
  '8ue1kZb/09N4z0tb5llNAqAgh4XXRl2moz43bZhr9QgAKGz0JTr688PMBEAxKpmLWZbnLK+D/cy3WgRAIQ4HF7MtzdleD9uZc3UIgCIcCi5mXZazvi7WM+9q',
  'EAAAEEgAFKCGuZj9t+TZXx/LmXv9CYDOHAIglfnXlwCAIlJ+O055nVCdAOhI/QLpzMF+BEAnfugBfjEP+xAAUEDatXja64WKBEAHahfgLXPxfALgZH7IAa4z',
  'H88lAAAgkAA4kboFuM+cPI8AOIkfaoBlzMtzCAAACCQATqBmAdYxN9sTAAAQSAA0pmIBtjE/2xIADfnhBdjHHG1HAABAIAHQiGoFOIZ52oYAAIBAAqABtQpw',
  'LHP1eAIAAAIJgIOpVIA2zNdjCQAACCQADqROAdoyZ48jAAAgkAA4iCoFOId5ewwBAACBBMAB1CjAuczd/QQAAAQSADupUIA+zN99BAAABBIAO6hPgL7M4e0E',
  'AAAEEgAbqU6AGszjbQQAAAQSAAAQSABs4LoJoBZzeT0BAACBBMBKKhOgJvN5HQEAAIEEwArqEqA2c3o5AQAAgQQAAAQSAAu5VgIYg3m9jAAAgEACAAACCYAF',
  'XCcBjMXcfkwAAEAgAQAAgQTAA66RAMZkft8nAAAgkAAAgEAC4A7XRwBjM8dvEwAAEEgAAEAgAXCDayOAOZjn1wkAAAgkAAAgkAC4wnURwFzM9T8JAAAIJAAA',
  'IJAAAIBAAuAd7xMBzMl8f0sAAEAgAQAAgQQAAAQSAK94fwhgbub8bwIAAAIJAAAIJAAAIJAA+Jf3hQAymPe/CAAACCQAACCQAACAQAIAAAIJgCcfCAFIY+4L',
  'AACIJAAAIJAAAIBAAgAAAsUHgA+CAGRKn//xAQAAiQQAAAQSAAAQSAAAQCABAACBBAAABIoOgPQ/AgKQLnkPRAcAAKQSAAAQSAAAQCABAACBBAAABBIAABBI',
  'AABAIAEAAIEEAAAEEgAAECg2AJL/+kcAfkvdB7EBAADJBAAABBIAABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQSAAAQCABAACBBAAABBIA',
  'ABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQSAAAQCABAACBBAAABIoNgC/PX3o/AgAFpO6D2AAAgGQCAAACCQAACCQAACCQAACAQAIAAAIJ',
  'AAAIJAAAIJAAAIBAAgAAAkUHQOpf/wjAL8l7IDoAACCVAACAQAIAAAIJAAAIJAAAIJAAAIBA8QGQ/EdAAJKlz//4AACARAIAAAIJAAAIJAAAIJAAePJBEIA0',
  '5r4AAIBIAgAAAgkAAAgkAAAgkAD4lw+EAGQw738RAAAQSAAAQCABAACBBMAr3hcCmJs5/5sAAIBAAgAAAgkAAAgkAN7x/hDAnMz3twQAAAQSAAAQSAAAQCAB',
  'cIX3iQDmYq7/SQAAQCABAACBBMANrosA5mCeXycAACCQAACAQALgDtdGAGMzx28TAAAQSAAAQCAB8IDrI4Axmd/3CQAACCQAACCQAFjANRLAWMztxwQAAAQS',
  'AAAQSAAs5DoJYAzm9TICAAACCQAACCQAVnCtBFCbOb2cAACAQAJgJXUJUJP5vI4AAIBAAmADlQlQi7m8ngAAgEACAAACCYCNXDcB1GAebyMAACCQANhBdQL0',
  'ZQ5vJwAAIJAA2El9AvRh/u4jAAAgkAA4gAoFOJe5u58AAIBAAuAgahTgHObtMQQAAAQSAAdSpQBtmbPHEQAAEEgAHEydArRhvh5LAABAIAHQgEoFOJa5ejwB',
  'AACBBEAjahXgGOZpGwIAAAIJgIZUK8A+5mg7AqAxP7wA25ifbQkAAAgkAE6gYgHWMTfbEwAAEEgAnETNAixjXp5DAJzIDzXAfebkeQQAAAQSACdTtwDXmY/n',
  'EgAd+CEHeMtcPJ8AgAL++vZ370c4VdrrhYoEQCdqF+AX87APAdCRH3ognTnYjwCAIlKuxVNeJ1QnADpTv0Aq868vAVCAQ8DF7L8dz/76WM7c608AAEAgAVCE',
  'GuZi1t+SZ31drGfe1SAACnEouJhtWc72etjOnKtDABTjcHAxy9Kc5XWwn/lWiwCAwkZfnqM/P8xMABSkknlt1CU66nPThrlWjwAoymHhtdGW6WjPS1vmWU0f',
  'frz8fOn9ENz2+dvn3o9AMd+fv/Z+hJssft6z/Ov61PsBgHUuS7ZSCFj8MB43AANwC8AjPWLA0ucRv/3XJgAGIQKAkVj+9fkQ4CAcJmAU5tUYBMBAHCqgOnNq',
  'HAIAAAIJgMGoa6Aq82ksAmBADhlQjbk0HgEwKIcNqMI8GpMAGJhDB/RmDo1LAAzO4QN6MX/GJgAm4BACZzN3xicAJuEwAmcxb+YgACbiUAKtmTPzEACTcTiB',
  'VsyXuQiACTmkwNHMlfkIgEk5rMBRzJM5CYCJObTAXubIvATA5BxeYCvzY24CIIBDDKxlbsxPAIRwmIGlzIsMAiCIQw08Yk7kEABhHG7gFvMhiwAI5JAD75kL',
  'eQRAKIcduDAPMgmAYA49YA7kEgDhHH7I5fxnEwAYAhDIuefDj5efL70fgjo+f/vc+xGAhix+LtwA8IbhAPNyvnlNAPAHQwLm41zzngDgKsMC5uE8c43PAPCQ',
  'zwXAmCx+7nEDwEOGCIzHueURAcAihgmMw3llCW8BsJq3BKAmi5813ACwmiED9TiXrCUA2MSwgTqcR7bwFgC7eUsA+rD42cMNALsZQnA+54693ABwKLcB0JbF',
  'z1HcAHAowwnacb44khsAmnEbAMew+GnBDQDNGFqwn3NEK24AOIXbAFjH4qc1NwCcwjCD5ZwXzuAGgNO5DYDrLH7OJADoRgjALxY/PXgLgG4MPXAO6McNACW4',
  'DSCNxU9vAoBShACzs/ipQgBQkhBgNhY/1QgAShMCjM7ipyoBwBCEAKOx+KlOADAUIUB1Fj+jEAAMSQhQjcXPaAQAQxMC9GbxMyoBwBSEAGez+BmdAGA6YoBW',
  'LH1mIgCYlhDgKBY/MxIATE8IsJXFz8wEAFHEAI9Y+qQQAMQSA1xY+iQSAPAkBhJZ+qQTAPCOGJiXpQ+/CQC4QwyMz9KH6wQALCQGxmHpw2MCADYSBHVY+LCe',
  'AICDCILzWPiwnwCARgTBcSx8OJ4AgBOJgscseziHAIDOkqPAsod+BAAUNkMcWPJQkwCASZwZC5Y6jE8AAECgj70fAAA4nwAAgEACAAACCQAACCQAACCQAACA',
  'QAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAAC',
  'CQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgk',
  'AAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAj0fxXv5HpJFEEtAAAAAElFTkSuQmCC',
].join('');

export default defineConfig({
  server: {
    port: 3000,
    host: '0.0.0.0',
  },
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: {
        name: 'Smart Meal Planner',
        short_name: 'Meal Planner',
        description: '智能搭配高性价比餐食，随时随地安排你的下一顿。',
        start_url: '/',
        display: 'standalone',
        background_color: '#ffffff',
        theme_color: '#4CAF50',
        lang: 'zh-CN',
        icons: [
          {
            src: 'icons/icon-192.svg',
            sizes: '192x192',
            type: 'image/svg+xml',
            purpose: 'any'
          },
          {
            src: ICON_192,
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any'
          },
          {
            src: 'icons/icon-512.svg',
            sizes: '512x512',
            type: 'image/svg+xml',
            purpose: 'any maskable'
          },
          {
            src: ICON_512,
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any maskable'
          }
        ]
      },
      workbox: {
        navigateFallback: '/index.html',
      }
    })
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '.'),
    }
  }
});
